default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'sekret') %>
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>

development:
  <<: *default
  database: citest_development

test:
  <<: *default
  database: citest_test

production:
  <<: *default
  database: citest_production
  username: citest
  password: <%= ENV["CITEST_DATABASE_PASSWORD"] %>
